# Generated by Django 2.1.7 on 2019-03-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
