# Generated by Django 2.1.7 on 2019-03-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20190303_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.CharField(default='admin', max_length=20),
        ),
    ]
