language: python

python:
  - 3.7.1

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py makemigrations --noinput
  - python manage.py migrate --noinput
  - python manage.py collectstatic

script:
  - python manage.py test questions
