language: python

matrix:
    include:
        - python: 3.7
          dist: xenial
          sudo: true

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py makemigrations
  - python manage.py migrate --noinput
  - python manage.py collectstatic

script:
  - python manage.py test questions
